/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedCarsRouteImport } from './routes/_authenticated/cars'
import { Route as AuthenticatedFindRouteImport } from './routes/_authenticated/find'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedSpotsIndexRouteImport } from './routes/_authenticated/spots/index'
import { Route as AuthenticatedSpotsSpotIdReservationsRouteImport } from './routes/_authenticated/spots/$spotId/reservations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCarsRoute = AuthenticatedCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFindRoute = AuthenticatedFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSpotsIndexRoute = AuthenticatedSpotsIndexRouteImport.update({
  id: '/spots/',
  path: '/spots/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSpotsSpotIdReservationsRoute =
  AuthenticatedSpotsSpotIdReservationsRouteImport.update({
    id: '/spots/$spotId/reservations',
    path: '/spots/$spotId/reservations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/cars': typeof AuthenticatedCarsRoute
  '/find': typeof AuthenticatedFindRoute
  '/home': typeof AuthenticatedHomeRoute
  '/spots/': typeof AuthenticatedSpotsIndexRoute
  '/spots/$spotId/reservations': typeof AuthenticatedSpotsSpotIdReservationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/cars': typeof AuthenticatedCarsRoute
  '/find': typeof AuthenticatedFindRoute
  '/home': typeof AuthenticatedHomeRoute
  '/spots': typeof AuthenticatedSpotsIndexRoute
  '/spots/$spotId/reservations': typeof AuthenticatedSpotsSpotIdReservationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/cars': typeof AuthenticatedCarsRoute
  '/_authenticated/find': typeof AuthenticatedFindRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/spots/': typeof AuthenticatedSpotsIndexRoute
  '/_authenticated/spots/$spotId/reservations': typeof AuthenticatedSpotsSpotIdReservationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/bookings'
    | '/cars'
    | '/find'
    | '/home'
    | '/spots/'
    | '/spots/$spotId/reservations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/bookings'
    | '/cars'
    | '/find'
    | '/home'
    | '/spots'
    | '/spots/$spotId/reservations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/bookings'
    | '/_authenticated/cars'
    | '/_authenticated/find'
    | '/_authenticated/home'
    | '/_authenticated/spots/'
    | '/_authenticated/spots/$spotId/reservations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cars': {
      id: '/_authenticated/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof AuthenticatedCarsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/find': {
      id: '/_authenticated/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof AuthenticatedFindRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spots/': {
      id: '/_authenticated/spots/'
      path: '/spots'
      fullPath: '/spots/'
      preLoaderRoute: typeof AuthenticatedSpotsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spots/$spotId/reservations': {
      id: '/_authenticated/spots/$spotId/reservations'
      path: '/spots/$spotId/reservations'
      fullPath: '/spots/$spotId/reservations'
      preLoaderRoute: typeof AuthenticatedSpotsSpotIdReservationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedCarsRoute: typeof AuthenticatedCarsRoute
  AuthenticatedFindRoute: typeof AuthenticatedFindRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedSpotsIndexRoute: typeof AuthenticatedSpotsIndexRoute
  AuthenticatedSpotsSpotIdReservationsRoute: typeof AuthenticatedSpotsSpotIdReservationsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedCarsRoute: AuthenticatedCarsRoute,
  AuthenticatedFindRoute: AuthenticatedFindRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedSpotsIndexRoute: AuthenticatedSpotsIndexRoute,
  AuthenticatedSpotsSpotIdReservationsRoute:
    AuthenticatedSpotsSpotIdReservationsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
